language: php

php:
    - '7.1'
    - '7.2'

cache:
  directories:
  - $HOME/.composer/cache


before_script:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [ "$deps" == "low" ]; then composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-dist; fi
