language: php

env:
    global:
        - EXT_MONGO_VERSION=1.5.2

php:
    - '7.1'
    - '7.2'

cache:
    directories:
        - $HOME/.composer/cache


before_script:
    - tpecl mongodb-${EXT_MONGO_VERSION} mongodb.so
    - php --ri mongodb
    - composer install --no-interaction --no-progress --no-suggest