language: php

php:
    - '7.1'

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - pecl install mongodb
    - travis_retry composer update

script:
    - vendor/bin/phpunit --exclude-group=Integration
