sudo: required

language: php

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - docker-compose --version
    - docker-compose up --build -d

script:
    - ./bin/tests
