version: '3'

services:
    php:
        build:
            context: ./docker/php
        user: "$UID:$GID"
        volumes:
            - "./:/var/www/app/:z"

    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: xhprof
        tmpfs:
            - /var/lib/mongodb
        ports:
            - "${MONGO_PORT}:27017"
        volumes:
            - "./docker/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

    mongo-express:
        image: mongo-express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
        ports:
            - "${MONGO_EXPRESS_PORT}:8081"
